# Generated by Django 5.1.6 on 2025-02-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=50)),
                ('cgpa', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
