# Generated by Django 5.1.6 on 2025-02-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
