# Generated by Django 5.1.6 on 2025-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('CSE', 'CSE (Core)'), ('Cybersecurity', 'Cybersecurity'), ('AI', 'Artificial Intelligence'), ('DataScience', 'Data Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('VLSI', 'VLSI Design'), ('Other', 'Other')], default='CSE', max_length=20),
        ),
    ]
