# Generated by Django 5.1.6 on 2025-04-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
